### ISSUE TITLE
A volte non genera la Regione da indovinare

### ISSUE THREAD

**Issue by pablitocalvo** [Genio2003/My_Website#2]
In modo più o meno casuale il programma non genera la regione da indovinare per cui l'utente non potrà mai indovinare ...

suggerimento : 
la riga incriminata è : 

`num = Math.floor(Math.random()*20);`

il numero deve essere tra 1 e 21 compresi  ma l'espressione quali numeri fornisce?

Vedi qui e fai le modifiche del caso ...
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_random

**Comment by Genio2003** [comment]
Si, sono al corrente di questo problema.
La riga: `num = Math.floor(Math.random()*20);`
Dovrebbe generare numeri random da 0 a 20 ed dovrebbe funzionare visto che il vettore con le regioni parte da "0".

`array1=new Array;
array1[0]="Lazio";
array1[1]="Abruzzo";
array1[2]="Calabria";
array1[3]="Campania";
array1[4]="Basilicata";
array1[5]="Emilia-Romagna";
array1[6]="Friuli-Venezia Giulia";
array1[7]="Liguria";
array1[8]="Lombardia";
array1[9]="Marche";
array1[10]="Molise";
array1[11]="Piemonte";
array1[12]="Puglia";
array1[13]="Sardegna";
array1[14]="Sicilia";
array1[15]="Toscana";
array1[16]="Trentino Alto Adige (P.A. Trento)";
array1[17]="Trentino Alto Adige (P.A. Bolzano)";
array1[18]="Umbria";
array1[19]="Veneto";
array1[20]="Valle d'Aosta";`

In più se faccio girare il file localmente non riscontro questo problema...

**Comment by pablitocalvo** [comment]
sul  repo veramente l'array parte da 1 ... 

La valle d'aosta è mai capitata ?

**Comment by Genio2003** [comment]
Okay....allora è quello il problema, ho cambiato l'algoritmo dei numeri casuali, ma non la numerazione del vettore....😅

**Comment by Genio2003** [comment]
Okay, ora funziona....
