### ISSUE TITLE
Evidenziare in verde i campi pubblici 

### ISSUE THREAD

**Issue by pablitocalvo** [Genio2003/My_Website#9]
magari ci avevi già pensato .. ma graficamente sarebbe carino che le informazioni che viaggiano sul acanale in chiaro (parametro pubblico, e le chiavi pubbliche) siano su sfondo verde o giu di li ..

**Comment by Genio2003** [comment]
Così?

![immagine](https://user-images.githubusercontent.com/42435587/118785792-7e14e780-b891-11eb-932f-59e1fc8cbb81.png)

**Comment by pablitocalvo** [comment]
Verde molto più chiaro ......

**Comment by Genio2003** [comment]
Effettivamente ora si vede molto meglio...

![immagine](https://user-images.githubusercontent.com/42435587/118790186-cfbf7100-b895-11eb-8446-847c38b746e6.png)
